FROM nvidia/cuda:12.9.1-devel-ubuntu24.04

#################################################################################################################
#           Global
#################################################################################################################
# apt-get to skip any interactive post-install configuration steps with DEBIAN_FRONTEND=noninteractive and apt-get install -y

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ARG DEBIAN_FRONTEND=noninteractive
ARG LIGHTGBM_GIT_REF=stable
ARG LIGHTGBM_GIT_URL=https://github.com/lightgbm-org/LightGBM.git

#################################################################################################################
#           Global Path Setting
#################################################################################################################

ENV CUDA_HOME=/usr/local/cuda
ENV LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${CUDA_HOME}/lib64
ENV LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/lib

ENV OPENCL_LIBRARIES=/usr/lib/x86_64-linux-gnu
ENV OPENCL_INCLUDE_DIR=/usr/include

#################################################################################################################
#           TINI
#################################################################################################################

# Install tini
ENV TINI_VERSION=v0.14.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini

#################################################################################################################
#           SYSTEM
#################################################################################################################
# update: downloads the package lists from the repositories and "updates" them to get information on the newest versions of packages and their
# dependencies. It will do this for all repositories and PPAs.

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    bzip2 \
    ca-certificates \
    intel-opencl-icd \
    libglib2.0-0 \
    libxext6 \
    libsm6 \
    libxrender1 \
    python3-pip \
    python3-virtualenv \
    git \
    vim \
    mercurial \
    subversion \
    cmake \
    libboost-dev \
    libboost-system-dev \
    libboost-filesystem-dev \
    ocl-icd-opencl-dev \
    gcc \
    g++ && \
    rm -rf /var/lib/apt/lists/*

# Add OpenCL ICD files for LightGBM
RUN mkdir -p /etc/OpenCL/vendors && \
    echo "libnvidia-opencl.so.1" > /etc/OpenCL/vendors/nvidia.icd


RUN pip install --break-system-packages numpy scipy scikit-learn jupyter notebook ipython pandas matplotlib

#################################################################################################################
#           LightGBM
#################################################################################################################

RUN cd /usr/local/src && mkdir lightgbm && cd lightgbm && \
    git clone \
        --recursive \
        "${LIGHTGBM_GIT_URL}" && \
    git -C ./LightGBM checkout ${LIGHTGBM_GIT_REF} && \
    cd LightGBM && \
    cmake -B build -S . \
        -DUSE_GPU=1 \
        -DOpenCL_LIBRARY="${OPENCL_LIBRARIES}/libOpenCL.so" \
        -DOpenCL_INCLUDE_DIR="${OPENCL_INCLUDE_DIR}" && \
    cmake --build build -j$(nproc --ignore=1)

ENV PATH=/usr/local/src/lightgbm/LightGBM:${PATH}

RUN /bin/bash -c "pip install build && cd /usr/local/src/lightgbm/LightGBM && sh ./build-python.sh install --precompile"

#################################################################################################################
#           System CleanUp
#################################################################################################################
# apt-get autoremove: used to remove packages that were automatically installed to satisfy dependencies for some package and that are no more needed.
# apt-get clean: removes the aptitude cache in /var/cache/apt/archives. You'd be amazed how much is in there! the only drawback is that the packages
# have to be downloaded again if you reinstall them.

RUN apt-get autoremove -y && apt-get clean && \
    rm -rf /var/lib/apt/lists/*

#################################################################################################################
#           JUPYTER
#################################################################################################################

# password: keras
# password key: --NotebookApp.password='sha1:98b767162d34:8da1bc3c75a0f29145769edc977375a373407824'

# Add a notebook profile.
RUN <<EOF
# shellcheck disable=SC2174
mkdir -p -m 700 ~/.jupyter/
echo "c.NotebookApp.ip = '*'" >> ~/.jupyter/jupyter_notebook_config.py
EOF

VOLUME /home
WORKDIR /home

# IPython
EXPOSE 8888

ENTRYPOINT ["/tini", "--"]
CMD ["/bin/bash -c", "jupyter notebook --allow-root --no-browser --NotebookApp.password='sha1:98b767162d34:8da1bc3c75a0f29145769edc977375a373407824'"]
